### ISSUE TITLE
Polymorphism issue in ReflectionGenerator

### ISSUE THREAD

**Issue by sciocoder** [FastEndpoints/FastEndpoints#813]
After upgrading the version from 5.30 to 5.31 the project build fails due to a problem in ReflectionGenerator.

I have created a [sample project](https://github.com/sciocoder/FastEndpointsPolymorphismIssue) to replicate the problem scenario.

The build fails with error
ReflectionData.g.cs(33,39): Error CS0144 : Cannot create an instance of the abstract type or interface 'Animal'

**Comment by dcube9** [comment]
We have the same issue, please fix it.

**Comment by dj-nitehawk** [comment]
thanks for reporting and the repro.
should be sorted with `v5.31.0.5-beta`

**Comment by sciocoder** [comment]
> thanks for reporting and the repro.
> 
> should be sorted with `v5.31.0.5-beta`

Thanks!
